language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
script:
    - pytest --cov=./
after_success:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t ${CODECOV_TOKEN}
